services:
  api-go:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.api-go
    ports: ["8080:8080"]
    env_file: ["../../.env"]
    depends_on: [db]

  workers-py:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.workers-py
    env_file: ["../../.env"]
    volumes:
      - ../../storage:/data/files
    depends_on: [db, mq]

  n8n:
    build:
      context: ../../
      dockerfile: integrations/n8n/Dockerfile
    env_file: ["../../integrations/n8n/n8n.env.example"]
    environment:
      N8N_USER_FOLDER: /home/node/.n8n
      NODES_EXCLUDE: '["n8n-nodes-base.localFileTrigger"]'
      PYTHONPATH: /workspace/apps/workers-py/src
      GRAPH_CLIENT_ID: ${GRAPH_CLIENT_ID}
    user: "root"
    ports: ["5678:5678"]
    volumes:
      - n8n_data:/home/node/.n8n
      - ../../:/workspace
    depends_on: [db, mq]

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoices
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data

  mq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]

volumes:
  pg_data:
  n8n_data:
